version: '2.1'

services:
  webapp:
    build:
      context: .
      dockerfile: ./src/webapp/Dockerfile
    ports:
      - "8080:8080"

  webproxy:
    depends_on:
      - webapp
    build:
      context: .
      dockerfile: ./src/proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
